#0000 Minor bug fix update to quartz
    * [QTZ-288] - SQL For Aquiring Triggers to Fire has Typo - Resulting in Job Recovery failing and other problems with Misfires
    * [QTZ-296] - OracleDelegate broken in 2.1.4 release (With NoSuchMethodError)
    * [QTZ-129] - Missing Serializable attributes/ids
    * [QTZ-179] - Possible bug with triggers left/stuck in ACQUIRED state
    * [QTZ-237] - storeTrigger not check the MisfireInstruction
    * [QTZ-254] - Fix PropertySettingJobFactory's warnings on FileScanJob
    * [QTZ-263] - Quartz job scheduler (in clustered configuration) does not recover stuck jobs after loss of database connectivity
    * [QTZ-269] - XMLSchedulingDataProcessorPlugin documentation refers to incorred job_scheduling_data XSD
    * [QTZ-270] - MisfireHandler Thread hangs forever on obtaining lock
    * [QTZ-271] - Repeat close "PreparedStatement"
    * [QTZ-273] - XMLSchedulingDataProcessorPlugin ignores time zones in ISO8601 start/end time
    * [QTZ-276] - Serial Version UID of  TimeOfDay changed in previous release
    * [QTZ-277] - Possible failure during recovery mode of scheduler startup when trigger is expired
    * [QTZ-278] - Bug in HSQLDB scripts
    * [QTZ-283] - MISFIRE_INSTRUCTION_IGNORE_MISFIRE_POLICY not working with JDBCJobStore