Banking report finished. CIT#470
There was a bug reported (see log below) that was caused by "Null value in the middle of the path, failed on administrationCentre.name"

The reason was a null in administrationCentre in PaymentIn and for the report is a sort on "administrationCentre.name" necessary.

The related class org.apache.cayenne.query.Ordering provides a method setPathExceptionSupressed(boolean pathExceptionSuppressed) to cope with that. 


12:27:54,392 [Foxtrot Single Worker Thread #1] ERROR ish.oncourse.controller.PrintController :481 - Error while populating reports. report:Banking Report 

org.apache.cayenne.exp.ExpressionException: [v.3.0-SNAPSHOT Sep 22 2008 12:58:20] Error evaluating expression 'administrationCentre.name' 
at org.apache.cayenne.exp.parser.SimpleNode.evaluate(SimpleNode.java:331) 
at org.apache.cayenne.query.Ordering.compare(Ordering.java:222) 
at org.apache.commons.collections.comparators.ComparatorChain.compare(ComparatorChain.java:277) 
at java.util.Arrays.mergeSort(Unknown Source) 
at java.util.Arrays.mergeSort(Unknown Source) 
at java.util.Arrays.mergeSort(Unknown Source) 
at java.util.Arrays.mergeSort(Unknown Source) 
at java.util.Arrays.mergeSort(Unknown Source) 
at java.util.Arrays.mergeSort(Unknown Source) 
at java.util.Arrays.mergeSort(Unknown Source) 
at java.util.Arrays.sort(Unknown Source) 
at java.util.Collections.sort(Unknown Source) 
at org.apache.cayenne.query.Ordering.orderList(Ordering.java:72) 
at ish.oncourse.controller.PrintController$1.run(PrintController.java:437) 
at foxtrot.AbstractWorkerThread$1.run(AbstractWorkerThread.java:40) 
at java.security.AccessController.doPrivileged(Native Method) 
at foxtrot.AbstractWorkerThread.runTask(AbstractWorkerThread.java:36) 
at foxtrot.workers.SingleWorkerThread.run(SingleWorkerThread.java:199) 
at foxtrot.workers.SingleWorkerThread.run(SingleWorkerThread.java:182) 
at java.lang.Thread.run(Unknown Source) 

Caused by: org.apache.cayenne.reflect.UnresolvablePathException: [v.3.0-SNAPSHOT Sep 22 2008 12:58:20] Null value in the middle of the path, failed on administrationCentre.name from <ish.oncourse.cayenne.PaymentIn@2898361, id=<ObjectId:PaymentIn, id=360>, state=committed, context=ish.oncourse.cayenne.CayenneContext@4e0563> at org.apache.cayenne.reflect.PropertyUtils.getProperty(PropertyUtils.java:110) at org.apache.cayenne.exp.parser.ASTObjPath.evaluateNode(ASTObjPath.java:49) at org.apache.cayenne.exp.parser.SimpleNode.evaluate(SimpleNode.java:327) ... 19 more